export const AuthConstants = {
  ATTEMPT_LOGIN: 'ATTEMPT_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGGED_OUT: 'LOGGED_OUT'
};

export const UtilityConstants = {
  OPEN_MENU: 'OPEN_MENU'
};

export const UserConstants = {
  UPDATING_PROFILE: 'UPDATING_PROFILE',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS'
}

export const ScoresConstants = {
  ADDING_SCORE: 'ADDING_SCORE',
  ADDED_SCORE: 'ADDED_SCORE',
  UPDATING_SCORE: 'UPDATING_SCORE',
  UPDATED_SCORE: 'UPDATED_SCORE',
  DELETING_SCORE: 'DELETING_SCORE',
  DELETED_SCORE: 'DELETED_SCORE'
};

export const CoursesConstants = {
  FETCH_ALL_COURSES: 'FETCH_ALL_COURSES',
  FETCH_ALL_COURSES_SUCCESS: 'FETCH_ALL_COURSES_SUCCESS',
  FETCH_ALL_COURSES_FAILURE: 'FETCH_ALL_COURSES_FAILURE',
  FETCH_COURSE: 'FETCH_COURSE',
  FETCH_COURSE_SUCCESS: 'FETCH_COURSE_SUCCESS',
  FETCH_COURSE_FAILURE: 'FETCH_COURSE_FAILURE',
  ADD_COURSE: 'ADD_COURSE',
  ADD_COURSE_SUCCESS: 'ADD_COURSE_SUCCESS',
  ADD_COURSE_FAILURE: 'ADD_COURSE_FAILURE'
}

export const TournamentConstants = {
  ADDING_TOURNAMENT: 'ADDING_TOURNAMENT'
};