export const AuthConstants = {
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
  ATTEMPT_LOGIN: 'ATTEMPT_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGGED_OUT: 'LOGGED_OUT'
};

export const UtilityConstants = {
  UPDATE_USER_FORM: 'UPDATE_USER_FORM'
};

export const ScorecardConstant = {
  FETCH_SCORECARD_LIST: 'FETCH_SCORECARDS',
  FETCH_SCORECARD_LIST_SUCCESS: 'FETCH_SCORECARD_LIST_SUCCESS',
  FETCH_SCORECARD_LIST_FAILURE: 'FETCH_SCORECARD_LIST_FAILURE',
  ADD_SCORECARD: 'ADD_SCORECARD',
  ADD_SCORECARD_SUCCESS: 'ADD_SCORECARD_SUCCESS',
  ADD_SCORECARD_FAILURE: 'ADD_SCORECARD_FAILURE',
  UPDATE_SCORECARD: 'UPDATE_SCORECARD',
  UPDATE_SCORECARD_SUCCESS: 'UPDATE_SCORECARD_SUCCESS',
  UPDATE_SCORECARD_FAILURE: 'UPDATE_SCORECARD_FAILURE'
}

export const TournamentConstants = {
  ADD_TOURNAMENT: 'ADD_TOURNAMENT',
  ADD_TOURNAMENT_ATTEMPT: 'ADD_TOURNAMENT_ATTEMPT',
  ADD_TOURNAMENT_SUCCESS: 'ADD_TOURNAMENT_SUCCESS',
  ADD_TOURNAMENT_FAILURE: 'ADD_TOURNAMENT_FAILURE'
}

export const UserConstants = {
  FETCH_USER: 'FETCH_USER',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_DETAILS: 'UPDATE_USER_DETAILS',
  UPDATE_USER_DETAILS_SUCCESS: 'UPDATE_USER_DETAILS_SUCCESS',
  UPDATE_USER_DETAILS_FAILURE: 'UPDATE_USER_DETAILS_FAILURE',
  INITIALIZE_FETCH_USER_DETAILS: 'INITIALIZE_FETCH_USER_DETAILS',
  FETCH_USER_DETAILS_PENDING: 'FETCH_USER_DETAILS_PENDING',
  FETCH_USER_DETAILS_FULFILLED: 'FETCH_USER_DETAILS_FULFILLED',
  FETCH_USER_DETAILS_REJECTED: 'FETCH_USER_DETAILS_REJECTED',
  FETCH_USER_TROPHIES_SUCCESS: 'FETCH_USER_TROPHIES_SUCCESS'
}

export const ScoresConstants = {
  ADD_SCORE: 'ADD_SCORE',
  ADD_SCORE_SUCCESS: 'ADD_SCORE_SUCCESS',
  ADD_SCORE_FAILURE: 'ADD_SCORE_FAILURE',
  UPDATE_SCORE: 'UPDATE_SCORE',
  UPDATE_SCORE_SUCCESS: 'UPDATE_SCORE_SUCCESS',
  UPDATE_SCORE_FAILURE: 'UPDATE_SCORE_FAILURE',
  DELETE_SCORE: 'DELETE_SCORE',
  DELETE_SCORE_SUCCESS: 'DELETE_SCORE_SUCCESS',
  DELETE_SCORE_FAILURE: 'DELETE_SCORE_FAILURE'
};

export const CoursesConstants = {
  FETCH_ALL_COURSES: 'FETCH_ALL_COURSES',
  FETCH_ALL_COURSES_SUCCESS: 'FETCH_ALL_COURSES_SUCCESS',
  FETCH_ALL_COURSES_FAILURE: 'FETCH_ALL_COURSES_FAILURE',
  FETCH_COURSE: 'FETCH_COURSE',
  FETCH_COURSE_SUCCESS: 'FETCH_COURSE_SUCCESS',
  FETCH_COURSE_FAILURE: 'FETCH_COURSE_FAILURE',
  ADD_COURSE: 'ADD_COURSE',
  ADD_COURSE_SUCCESS: 'ADD_COURSE_SUCCESS',
  ADD_COURSE_FAILURE: 'ADD_COURSE_FAILURE'
}
